name: BuildWebhook
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...
        
      - uses: actions/upload-artifact@v2
        with:
          name: WebHook Personal Builds
          path: webhook
